### ISSUE TITLE
USER STORY: Submit a Poll Response

### ISSUE THREAD

**Issue by gayatrig19** [gayatrig19/My-First-Agile-Project#4]
In order to **provide anonymous feedback** as a **user**, I can **choose to hide my identity in the poll response.**

## Acceptance Criteria

* The option should be provided as a checkbox.
* The checkbox should be “checked” by default.
* The option should appear next to the submit button.
* After submitting the default submission confirmation should be adjusted to include the user name.

## Tasks
- [x] Update the view: the poll design (HTML and CSS) to include the checkbox and to show the name of the submitter
- [x] Create a new field in the model to track the username
- [x] Update the controller function
- [x] Update unit tests scripts
- [x] Test the functionality
