### ISSUE TITLE
USER STORY: Publish a Poll

### ISSUE THREAD

**Issue by gayatrig19** [gayatrig19/My-First-Agile-Project#5]
In order **to automatically hide the poll** as **an administrator**, I can **pick the expiry date while publishing the poll.**

## Acceptance Criteria

* The poll should disappear at 11:59 PM on the target date .
* The real estate of the "Poll" should be reserved on the home page. A message that says "Stay Tuned, a new poll is coming soon" should appear if no other Poll is active.
* The administrator expiry date should be at least 3 days after the current date.

## Tasks
- [x] Update the admin module view: the poll design (HTML and CSS) to include date picker.
- [x] Update the website view: show "Stay tuned, a new poll is coming soon" .
- [x] Create a JavaScript function to validate the expiry date is at least after 3 days.
- [x] Create a job to check expired Polls everyday at 11:59 PM and Hide them.
- [x] Update the controller function.
- [x] Update unit tests scripts.
- [x] Test the functionality.
